name: Test Unix Script

on:
  push:
    paths:
      - 'check.sh'
      - 'tests/**'
      - '.github/workflows/test-unix.yml'
  pull_request:
    paths:
      - 'check.sh'
      - 'tests/**'
  workflow_dispatch:

jobs:
  test-unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Install bashunit
        run: |
          git clone https://github.com/TypedDevs/bashunit.git
          cd bashunit
          sudo make install
          cd ..
      
      - name: Run tests
        run: |
          cd tests
          chmod +x test_check.sh
          bashunit test_check.sh
      
      - name: Run actual script
        if: success()
        run: |
          chmod +x check.sh
          ./check.sh
