name: Test Unix Script

on:
  push:
    paths:
      - 'check.sh'
      - 'tests/**'
      - '.github/workflows/test-unix.yml'
  pull_request:
    paths:
      - 'check.sh'
      - 'tests/**'
  workflow_dispatch:

jobs:
  test-unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install bashunit
        run: |
          curl -s https://bashunit.typeddevs.com/install.sh > install.sh
          chmod +x install.sh
          ./install.sh
      
      - name: Run tests
        env:
          BASHUNIT_DEFAULT_PATH: tests/test_check.sh
          BASHUNIT_SIMPLE_OUTPUT: true
          BASHUNIT_SHOW_HEADER: false
        run: |
          cd tests
          chmod +x test_check.sh
          bashunit
      
      - name: Run actual script
        if: success()
        run: |
          chmod +x check.sh
          ./check.sh
